os: linux
dist: focal
language: python
jobs:
  include:
    - python: pypy3
      env: TOXENV=pypy3
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: 3.7
      env: TOXENV=lint
    - python: 3.8
      env: TOXENV=docs

install: pip install tox-travis

script: tox

after_success: coveralls

before_deploy:
  - git describe --tags > VERSION

deploy:
  provider: pypi
  username: nickw444-deploy
  password: "$PYPI_PASSWORD"
  on:
    tags: true
    python: 3.6
